name: Deploy project to Cloudflare Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.repository == 'Haocen/niimblue'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Check code
        run: npm run sv-check

      - name: Build
        run: npx vite build --base="${{ steps.pages.outputs.base_path || '/' }}"
        env:
          COMMIT_HASH: ${{github.sha}}

      - name: Generate Sitemap
        run: |
          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
          <urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">
            <url>
              <loc>$PAGE_URL</loc>
              <lastmod>$LAST_MODIFIED</lastmod>
            </url>
          </urlset>" > ./dist/sitemap.xml
        env:
          PAGE_URL: ${{ steps.pages.outputs.origin }}
          LAST_MODIFIED: ${{ github.event.repository.updated_at }}

      - name: Deploy Niimblue
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "3.72.2" # A version later than 3.48.0 is required for uploading env vars from wrangler.toml
          apiToken: ${{ secrets.HX_CF_API_TOKEN }}
          accountId: ${{ secrets.HX_CLOUDFLARE_ACCOUNT_ID }}
          command: |
            pages deploy ./dist --project-name=niimblue
            pages deploy ./dist --project-name=niimbot

